### ISSUE TITLE
targets incompatible with the current platform are selected

### ISSUE THREAD

**Issue by alokpr** [bazel-contrib/target-determinator#43]
```
$ cat .bazelrc
build --cxxopt -std=c++17
build:asan --compilation_mode dbg
build:asan --copt -fsanitize=address
build:asan --linkopt -fsanitize=address
```

```
$ cat BUILD.bazel
cc_test(
    name = "foo_test",
    srcs = ["foo_test.cc"],
    target_compatible_with = select({
        "//:asan_config": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)

config_setting(
    name = "asan_config",
    values = {
        "copt": "-fsanitize=address",
    },
)
```

```
$ target-determinator --bazel-opts="--config=asan" main
//:foo_test
```

**Comment by alokpr** [comment]
I think for each affected target `bazel cquery --config=asan "config(target, id)"` must be called to check if the target should be selected.

https://bazel.build/query/cquery#config

**Comment by alokpr** [comment]
Thanks for the pointers. I will give it a shot.

**Comment by alokpr** [comment]
Hi Daniel, I looked into your suggestions. I have not yet decided which option to use. But was wondering if the second one is even feasible. Is this information available somewhere - "if we knew the configuration we wanted to build for"? Is there a command to query the configuration id given bazel-opts?

**Comment by illicitonion** [comment]
> Is there a command to query the configuration id given bazel-opts?

After running `bazel cquery`, if you run `bazel config`, you'll get a dump of configurations which exist - some will be explicitly labelled as "exec" or "host" configs, and others won't be. I _believe_ any that _aren't_ exec or host, are target configs which we may be attempting to build for. But I'll be honest - I'm not completely sure on this part. It definitely leads me to prefer approach 1, but if someone wants to do the research to work out a viable way to do 2, that could be interesting too :)
