### ISSUE TITLE
bazel-opts are not passed to bazel-config command

### ISSUE THREAD

**Issue by alokpr** [bazel-contrib/target-determinator#45]
According to bazel-config documentation:

> Usage: bazel config <options> [<config_id> | <config_id> <config_id>]
> 
> Displays the given configuration objects, if they can be found in the Skyframe cache. The best way
> to use this command is to first run a build (or cquery), and then immediately run the config
> command to view the configuration. **Note that any flags passed to build (or cquery) must also be
> passed to config, or else the Skyframe cache will be evicted and no configurations will be found.**

Not sure if `--dump_all` overrides this. But may be a good idea to pass bazel-opts to the config command anyways.

**Comment by illicitonion** [comment]
Ooh good catch! Can I tempt you to send over a PR?

**Comment by alokpr** [comment]
Sure, will do
