### ISSUE TITLE
deadlock in hashTarget -> build.Target_RULE -> hashRule

### ISSUE THREAD

**Issue by com6056** [bazel-contrib/target-determinator#57]
Haven't narrowed it down exactly yet but seems there is a deadlock somewhere in the following flow:

`PrefillCache` calls `queryInfo.TargetHashCache.Hash` which holds onto `entry.hashLock.Lock()` while it calls `hashTarget`.

`hashTarget`, in the case of `build.Target_RULE`, calls `hashRule`, which eventually calls `thc.Hash` again which blocks on `entry.hashLock.Lock()` indefinitely.

Trying to narrow down exactly what is going on but figured I'd surface this in case someone else can figure it out faster 😛

**Comment by com6056** [comment]
In our case, I _think_ I see this happening with `@org_golang_x_tools//go/analysis:analysis` and `@io_bazel_rules_go//:go_context_data`, but need to validate.

**Comment by com6056** [comment]
Looks like it might be related to `nogo` usage? I added some messy logging to see what was holding onto the lock and got this:
```
{@io_bazel_rules_go//:go_context_data {0a4d9d48f377253da730a871cf79a6613f4c9221c23ad1ec757a57e84ac16090}} still has the lock
{//:foo_nogo {0a4d9d48f377253da730a871cf79a6613f4c9221c23ad1ec757a57e84ac16090}} still has the lock
{@io_bazel_rules_nogo//:nogo {0a4d9d48f377253da730a871cf79a6613f4c9221c23ad1ec757a57e84ac16090}} still has the lock
{//tools/bazel/analyzers/unusedresult {ef509650ff1c02d363060ca6742b0e13ff929a68634d1c51973a4d2bca6cb636}} still has the lock
{@org_golang_x_tools//go/analysis {ef509650ff1c02d363060ca6742b0e13ff929a68634d1c51973a4d2bca6cb636}} still has the lock
{//:mux_nogo_actual {ef509650ff1c02d363060ca6742b0e13ff929a68634d1c51973a4d2bca6cb636}} still has the lock
```

**Comment by illicitonion** [comment]
We strongly assume that the dependency graph returned in cquery is acyclic, because Bazel is _meant_ to guarantee that; a deadlock here would suggest a cycle in that graph.

We probably _should_ make this code more resilient to cycles, but regardless if you can put together a small repro repo so we can investigate why Bazel is returning a cycle here (and whether it's a bug in Bazel), that'd be really handy!

**Comment by com6056** [comment]
Let me know if you are able to reproduce with https://github.com/com6056/td-cycle-repro or not or if I can provide any additional info to help out, thanks! 🙌

**Comment by illicitonion** [comment]
I do reproduce - thanks so much for the reduced test case, I'll get a fix up soon!
