### ISSUE TITLE
Provide an option to override bazel command 

### ISSUE THREAD

**Issue by alokpr** [bazel-contrib/target-determinator#80]
The driver runs 'build' or 'test' depending on the target type. The 'test' command however does not make sense for some build configs like clang-tidy which only performs static analysis.

The driver should provide a 'command' option which can be set to either 'build' or 'auto' (current behavior)

**Comment by alokpr** [comment]
Happy to send PR if the feature request sounds reasonable

**Comment by illicitonion** [comment]
I think this sounds reasonable and would gladly review a PR for it :)

This is about the limit of the kind of complexity/configurability I think is reasonable to add to `driver` though - in general `driver` is intended as more of an example which may work for simple use-cases. If you're looking to add much more functionality to it, I'd consider writing your own tool which uses the `WalkAffectedTargets` API (which is intended as a building block for a more complex CI driver), as in my experience everyone wants _slightly_ different CI set-ups.

**Comment by illicitonion** [comment]
Fixed in https://github.com/bazel-contrib/target-determinator/pull/92
